version: "3"
services:
  app:
    build:
      context: .
    tty: true
    init: true
    working_dir: /app/learing-optional-catch-all-route
    volumes:
      - ./src:/app/learing-optional-catch-all-route
    ports:
      - "3999:3999"